In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
warehouse =  {
    "P1": 0,
    "P2": 0,
    "P3": 0,
    "E4": 0,
    "E5": 0,
    "E6": 0,
    "E7": 0,
    "E8": 0,
    "E9": 0,
    "E10": 0,
    "E11": 0,
    "E12": 0,
    "E13": 0,
    "E14": 0,
    "E15": 0,
    "E16": 0,
    "E17": 0,
    "E18": 0,
    "E19": 0,
    "E20": 0,
    "E26": 0,
    "E29": 0,
    "E30": 0,
    "E31": 0,
    "E49": 0,
    "E50": 0,
    "E51": 0,
    "E54": 0,
    "E55": 0,
    "E56": 0
}

In [4]:
for prod in warehouse.keys():
    warehouse[prod] += 100

for prod in ["E16", "E17", "E26"]:
    warehouse[prod] += 200

In [122]:
requirements = {
    "P1": ["K21", "K24", "K27", "E26", "E51"],
    "P2": ["K22", "K24", "K27", "E26", "E56"],
    "P3": ["K23", "K24", "K27", "E26", "E31"],
    "E4": ["K35", "K35", "K36", "K52", *["K53"]*36],
    "E5": ["K35", "K35", "K36", "K57", *["K58"]*36],
    "E6": ["K33",*["K34"]*36, "K35", "K35", "K36"],
    "E7": ["K35", "K35", "K37", "K38", "K52",  *["K53"]*36],
    "E8": ["K35", "K35", "K37", "K38", "K57", *["K58"]*36],
    "E9": ["K33",  *["K34"]*36, "K35", "K35", "K37", "K38"],
    "E10": ["K32", "K39"],
    "E11": ["K32", "K39"],
    "E12": ["K32", "K39"],
    "E13": ["K32", "K39"],
    "E14": ["K32", "K39"],
    "E15": ["K32", "K39"],
    "E16": ["K24", "K28", "K40", "K41", "K42", "K42"],
    "E17": ["K43", "K44", "K45", "K46"],
    "E18": ["K28", "K28", "K28", "K32", "K59", "K59"],
    "E19": ["K28", "K28", "K28", "K28", "K32", "K59", "K59"],
    "E20": ["K28", "K28", "K28", "K28", "K28", "K32", "K59", "K59"],
    "E26": ["K44", "K44", "K47", "K48", "K48"],
    "E29": ["K24", "K24", "K25", "K25", "E9", "E15", "E20"],
    "E30": ["K24", "K24", "K25", "K25", "E6", "E12", "E29"],
    "E31": ["K24", "K27", "E16", "E17", "E30"],
    "E49": ["K24", "K24", "K25", "K25", "E7", "E13", "E18"],
    "E50": ["K24", "K24", "K25", "K25", "E4", "E10", "E49"],
    "E51": ["K24", "K27", "E16", "E17", "E50"],
    "E54": ["K24", "K24", "K25", "K25", "E8", "E14", "E19"],
    "E55": ["K24", "K24", "K25", "K25", "E5", "E11", "E54"],
    "E56": ["K24", "K27", "E16", "E17", "E55"]
}

In [123]:
def step(parts):
    new_parts = []
    for part in parts:
        if part in requirements.keys():
            new_parts += requirements[part]
        else:
            new_parts.append(part)
    return new_parts

In [209]:
parts = [*["P1"]*100,*["P3"]*100,*["P3"]*100]

In [236]:
theoretical_warehouse = []
for part, quantity in warehouse.items():
    theoretical_warehouse += [*[part]*quantity]

In [240]:
old = theoretical_warehouse
new = step(theoretical_warehouse)
while len(old) != len(new):
    old = new
    new = step(new)

In [244]:
a = Counter(old)

In [246]:
b = Counter(parts)

In [247]:
a-b

Counter({'K24': 3900,
         'K27': 300,
         'K44': 1200,
         'K47': 300,
         'K48': 600,
         'K28': 5300,
         'K40': 600,
         'K41': 600,
         'K42': 1200,
         'K43': 600,
         'K45': 600,
         'K46': 600,
         'K25': 3000,
         'K35': 4200,
         'K36': 900,
         'K52': 700,
         'K53': 25200,
         'K32': 3300,
         'K39': 2100,
         'K37': 1200,
         'K38': 1200,
         'K59': 2400,
         'K22': 100,
         'K57': 900,
         'K58': 32400,
         'K33': 500,
         'K34': 18000})

In [222]:
p = np.array(
    [[100, 150, 150, 150],
    [100, 100, 100, 50],
    [100, 100, 50, 50]]
)

In [233]:
a = np.array(
    [[1,0,0],
    [0,1,0],
    [0,0,1],
    [7,7,7],
    [4,4,4],
    [2,2,2],
    [4,5,6],
    [3,3,3],
    [0,0,2],
    [0,0,72],
    [4,4,4],
    [1,1,1],
    [1,1,1],
    [1,1,1],
    [2,2,2],
    [1,1,1],
    [1,1,1],
    [2,2,2],
    [1,1,1],
    [3,3,3],
    [1,1,1],
    [1,1,1],
    [1,1,1],
    [2,2,2],
    [2,0,0],
    [72,0,0],
    [0,2,0],
    [0,72,0],
    [2,2,2]]
)
a@p

array([[  100,   150,   150,   150],
       [  100,   100,   100,    50],
       [  100,   100,    50,    50],
       [ 2100,  2450,  2100,  1750],
       [ 1200,  1400,  1200,  1000],
       [  600,   700,   600,   500],
       [ 1500,  1700,  1400,  1150],
       [  900,  1050,   900,   750],
       [  200,   200,   100,   100],
       [ 7200,  7200,  3600,  3600],
       [ 1200,  1400,  1200,  1000],
       [  300,   350,   300,   250],
       [  300,   350,   300,   250],
       [  300,   350,   300,   250],
       [  600,   700,   600,   500],
       [  300,   350,   300,   250],
       [  300,   350,   300,   250],
       [  600,   700,   600,   500],
       [  300,   350,   300,   250],
       [  900,  1050,   900,   750],
       [  300,   350,   300,   250],
       [  300,   350,   300,   250],
       [  300,   350,   300,   250],
       [  600,   700,   600,   500],
       [  200,   300,   300,   300],
       [ 7200, 10800, 10800, 10800],
       [  200,   200,   200,   100],
 

In [232]:
np.sum(a@p, axis=1)

array([  550,   350,   300,  8400,  4800,  2400,  5750,  3600,   600,
       21600,  4800,  1200,  1200,  1200,  2400,  1200,  1200,  2400,
        1200,  3600,  1200,  1200,  1200,  2400,  1100, 39600,   700,
       25200,  2400])

In [234]:
np.sum(a@p, axis=0)

array([36000, 41950, 35900, 29900])